name: Build APK

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest    # <--- заменил с ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip openjdk-17-jdk python3-pip \
            autoconf libtool pkg-config zlib1g-dev \
            libncurses5-dev libncursesw5-dev \
            cmake libffi-dev libssl-dev

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      - name: Remove Python tests BEFORE build
        run: |
          sudo rm -rf /usr/lib/python3.9/test
          sudo rm -rf /usr/lib/python3.9/lib-dynload/test
          sudo rm -rf /usr/lib/python3.9/unittest
          rm -rf ~/.buildozer/android/platform/build-*/build/other_builds/python3

      - name: Build APK
        run: |
          export PYTHONHASHSEED=0
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: obd2-apk
          path: bin/*.apk
